# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Snapshot deploy

on:
  push:
    branches:
      - 'main'
      - '2022.06.x'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # Maven Distribution Server (step creates .m2/settings.xml)
          server-id: 'sonatype-central'
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_TOKEN
      - name: Publish SNAPSHOT to sonatype central with Apache Maven
        env:
          SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SONATYPE_TOKEN:  ${{ secrets.OSSRH_TOKEN }}
        run: mvn --batch-mode deploy -P deploy-to-sonatype 
